appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32977c4e246e0700cece4c
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: L0aGISzrtSLNp6fteQTDGA+Vl2Gum8uGvC7SW+CVhMfjB7nr3ysou9zA93ZUXZk4bGHNV39uuIsJTlT7uKuhIReJq5MHcVqPEod6x60vBcwlZ4jIxmWIGO2YgYZTtkBniao6kx++9JaBXYqHWBAmxzBgjlIGB8S9qJt1kFcSxieI6/nIt3u0yFrvqANdBcaiuj2ywJ+Q7kT4B7JUc7SdMS9j1ce0mNNyRO/eQG3sCCI5ZE/lWw0JPlRx2zNR9ctGa5fWy3hyPbN4Wm8eyy2U9nHOsDS6LuFAWt1zKP4yzz5calraArNraPyl374nFIqWAVno45LGLdrm/RIctXz0J4CIVsiftsivxSOrvMPM677IFauat0t8TOIeqIoWokDd8TGh4ZOjscIdBq5shJiYeRNStfijdPMhQTzsnKq/xQ9STQJvXKGFR2hj0zYgRVEbAE/A7Il2C6ehCFVa1ZlylCH3yENzAKeENQFQqlRj2Z2NdBK0c9g75kP3NlgjmGC4aTv3xADgjha1pyUvZZbTdayAaWJxgO98nSz2aSSQp5JyoXTuBAvXkOSAqZerDt/4gYu05Nh5y3QOPmgXF0vTDZqNMAkbVvO/V4Ee275q+KwC4OX9HsF4DlcacS2XluLNKVxOTxKDH9zmwgcDuHwe7Rci7dl1jWaPQipuVavbrWw=}
